// Generated by CoffeeScript 1.3.3
(function() {
  var app, port;

  global.express = require('express');

  global.forms = require('forms');

  global.app = app = express();

  require("" + __dirname + "/src/configuration");

  require("" + __dirname + "/src/models/database");

  require("" + __dirname + "/src/models/user");

  require("" + __dirname + "/src/controllers/user_controller");

  require("" + __dirname + "/src/controllers/home_controller");

  app.listen(port = 3000);

  console.log("Lit server listening on port %d in %s mode", port, app.settings.env);

}).call(this);
