// Generated by CoffeeScript 1.3.3
(function() {
  var fields, reg_form, validators, widgets;

  fields = forms.fields;

  validators = forms.validators;

  widgets = forms.widgets;

  reg_form = forms.create({
    firstname: fields.string({
      required: false
    }),
    lastname: fields.string({
      required: false
    }),
    email: fields.email({
      required: true
    }),
    password: fields.password({
      required: true
    }),
    confirm: fields.password({
      required: true,
      validators: [validators.matchField('password')]
    })
  });

  app.get('/user/register', function(req, res) {
    return res.render('register', {
      locals: {
        form: reg_form.toHTML()
      }
    });
  });

  app.get('/user/login', function(req, res) {
    return res.json([{}]);
  });

  app.post('/user/login', function(req, res) {
    return res.json([{}]);
  });

  app.get('/user/logout', function(req, res) {
    return res.json([{}]);
  });

  app.post('/user', function(req, res) {
    return reg_form.handle(req, {
      success: function(form) {
        return console.log(form.data);
      },
      error: function(form) {
        var aform;
        console.log('oops');
        aform = reg_form.bind(form.data);
        return res.render('register', {
          locals: {
            form: aform.toHTML()
          }
        });
      }
    });
  });

}).call(this);
