// Generated by CoffeeScript 1.3.3
(function() {

  global.mongoose = require('mongoose');

  global.Schema = mongoose.Schema;

  global.ObjectId = Schema.ObjectId;

  mongoose.connect("mongodb://localhost:27017/lit2012");

}).call(this);
